import Head from 'next/head';
import { HeroSection, Navbar } from '../components';

const Home = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <Navbar />
      <HeroSection />

    </main>
  </>
);
export default Home;
